name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get -y update
        sudo apt-get -y install ocaml-nox dune
    - name: Build
      run: dune build
    - name: Test
      run: dune test
